"""Add Enum Order_State

Revision ID: a6a2760f6945
Revises: a623e1d654e4
Create Date: 2026-06-17 15:20:01.804036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a2760f6945'
down_revision: Union[str, Sequence[str], None] = 'a623e1d654e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_order', 'state',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('PENDING', 'PAID', 'SHIPPED', 'CANCELLED', name='order_state', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_order', 'state',
               existing_type=sa.Enum('PENDING', 'PAID', 'SHIPPED', 'CANCELLED', name='order_state', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
