"""Add ProductOrder (Many to Many)

Revision ID: e21e34247da2
Revises: 36e458814a01
Create Date: 2026-06-17 16:41:51.356150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21e34247da2'
down_revision: Union[str, Sequence[str], None] = '36e458814a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_order',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'order_id')
    )
    op.drop_constraint(op.f('customer_order_product_id_fkey'), 'customer_order', type_='foreignkey')
    op.drop_column('customer_order', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('customer_order_product_id_fkey'), 'customer_order', 'product', ['product_id'], ['id'])
    op.drop_table('product_order')
    # ### end Alembic commands ###
