from model.human import Human
from model.wolf import Wolf
from model.dice import Dice

human = Human(12,12,12,12,0,0)
wolf = Wolf(12,12,12,12,1,1)
human.hit(wolf, Dice.DICE_FOUR)
print(human.current_life)
print(wolf.current_life)
print("------------------")
wolf.hit(human, Dice.DICE_FOUR)
print(human.current_life)
print(wolf.current_life)
print("------------------")
human.hit(wolf, Dice.DICE_FOUR)
print(human.current_life)
print(wolf.current_life)
print("------------------")
wolf.hit(human, Dice.DICE_FOUR)
print(human.current_life)
print(wolf.current_life)
print("------------------")
human.hit(wolf, Dice.DICE_FOUR)
print(human.current_life)
print(wolf.current_life)
print("------------------")
wolf.hit(human, Dice.DICE_FOUR)
print(human.current_life)
print(wolf.current_life)
print("------------------")
human.hit(wolf, Dice.DICE_FOUR)
print(human.current_life)
print(wolf.current_life)
print("------------------")
wolf.hit(human, Dice.DICE_FOUR)
print(human.current_life)
print(wolf.current_life)
print("------------------")